/*
 * Generated by gdbus-codegen 2.56.4. DO NOT EDIT.
 *
 * The license of this code is the same as for the D-Bus interface description
 * it was derived from.
 */

#ifndef __PLAYBACK_H__
#define __PLAYBACK_H__

#include <gio/gio.h>

G_BEGIN_DECLS


/* ------------------------------------------------------------------------ */
/* Declarations for org.hunesion.app.playback */

#define TYPE_org_hunesion_app_playback (org_hunesion_app_playback_get_type ())
#define org_hunesion_app_playback(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), TYPE_org_hunesion_app_playback, OrgHunesionAppPlayback))
#define IS_org_hunesion_app_playback(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), TYPE_org_hunesion_app_playback))
#define org_hunesion_app_playback_GET_IFACE(o) (G_TYPE_INSTANCE_GET_INTERFACE ((o), TYPE_org_hunesion_app_playback, OrgHunesionAppPlaybackIface))

struct _OrgHunesionAppPlayback;
typedef struct _OrgHunesionAppPlayback OrgHunesionAppPlayback;
typedef struct _OrgHunesionAppPlaybackIface OrgHunesionAppPlaybackIface;

struct _OrgHunesionAppPlaybackIface
{
  GTypeInterface parent_iface;

  gboolean (*handle_invoke_client_action_callback) (
    OrgHunesionAppPlayback *object,
    GDBusMethodInvocation *invocation,
    guint arg_seq,
    const gchar *arg_json);

};

GType org_hunesion_app_playback_get_type (void) G_GNUC_CONST;

GDBusInterfaceInfo *org_hunesion_app_playback_interface_info (void);
guint org_hunesion_app_playback_override_properties (GObjectClass *klass, guint property_id_begin);


/* D-Bus method call completion functions: */
void org_hunesion_app_playback_complete_invoke_client_action_callback (
    OrgHunesionAppPlayback *object,
    GDBusMethodInvocation *invocation);



/* D-Bus method calls: */
void org_hunesion_app_playback_call_invoke_client_action_callback (
    OrgHunesionAppPlayback *proxy,
    guint arg_seq,
    const gchar *arg_json,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data);

gboolean org_hunesion_app_playback_call_invoke_client_action_callback_finish (
    OrgHunesionAppPlayback *proxy,
    GAsyncResult *res,
    GError **error);

gboolean org_hunesion_app_playback_call_invoke_client_action_callback_sync (
    OrgHunesionAppPlayback *proxy,
    guint arg_seq,
    const gchar *arg_json,
    GCancellable *cancellable,
    GError **error);



/* ---- */

#define TYPE_org_hunesion_app_playback_PROXY (org_hunesion_app_playback_proxy_get_type ())
#define org_hunesion_app_playback_PROXY(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), TYPE_org_hunesion_app_playback_PROXY, OrgHunesionAppPlaybackProxy))
#define org_hunesion_app_playback_PROXY_CLASS(k) (G_TYPE_CHECK_CLASS_CAST ((k), TYPE_org_hunesion_app_playback_PROXY, OrgHunesionAppPlaybackProxyClass))
#define org_hunesion_app_playback_PROXY_GET_CLASS(o) (G_TYPE_INSTANCE_GET_CLASS ((o), TYPE_org_hunesion_app_playback_PROXY, OrgHunesionAppPlaybackProxyClass))
#define IS_org_hunesion_app_playback_PROXY(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), TYPE_org_hunesion_app_playback_PROXY))
#define IS_org_hunesion_app_playback_PROXY_CLASS(k) (G_TYPE_CHECK_CLASS_TYPE ((k), TYPE_org_hunesion_app_playback_PROXY))

typedef struct _OrgHunesionAppPlaybackProxy OrgHunesionAppPlaybackProxy;
typedef struct _OrgHunesionAppPlaybackProxyClass OrgHunesionAppPlaybackProxyClass;
typedef struct _OrgHunesionAppPlaybackProxyPrivate OrgHunesionAppPlaybackProxyPrivate;

struct _OrgHunesionAppPlaybackProxy
{
  /*< private >*/
  GDBusProxy parent_instance;
  OrgHunesionAppPlaybackProxyPrivate *priv;
};

struct _OrgHunesionAppPlaybackProxyClass
{
  GDBusProxyClass parent_class;
};

GType org_hunesion_app_playback_proxy_get_type (void) G_GNUC_CONST;

#if GLIB_CHECK_VERSION(2, 44, 0)
G_DEFINE_AUTOPTR_CLEANUP_FUNC (OrgHunesionAppPlaybackProxy, g_object_unref)
#endif

void org_hunesion_app_playback_proxy_new (
    GDBusConnection     *connection,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GAsyncReadyCallback  callback,
    gpointer             user_data);
OrgHunesionAppPlayback *org_hunesion_app_playback_proxy_new_finish (
    GAsyncResult        *res,
    GError             **error);
OrgHunesionAppPlayback *org_hunesion_app_playback_proxy_new_sync (
    GDBusConnection     *connection,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GError             **error);

void org_hunesion_app_playback_proxy_new_for_bus (
    GBusType             bus_type,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GAsyncReadyCallback  callback,
    gpointer             user_data);
OrgHunesionAppPlayback *org_hunesion_app_playback_proxy_new_for_bus_finish (
    GAsyncResult        *res,
    GError             **error);
OrgHunesionAppPlayback *org_hunesion_app_playback_proxy_new_for_bus_sync (
    GBusType             bus_type,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GError             **error);


/* ---- */

#define TYPE_org_hunesion_app_playback_SKELETON (org_hunesion_app_playback_skeleton_get_type ())
#define org_hunesion_app_playback_SKELETON(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), TYPE_org_hunesion_app_playback_SKELETON, OrgHunesionAppPlaybackSkeleton))
#define org_hunesion_app_playback_SKELETON_CLASS(k) (G_TYPE_CHECK_CLASS_CAST ((k), TYPE_org_hunesion_app_playback_SKELETON, OrgHunesionAppPlaybackSkeletonClass))
#define org_hunesion_app_playback_SKELETON_GET_CLASS(o) (G_TYPE_INSTANCE_GET_CLASS ((o), TYPE_org_hunesion_app_playback_SKELETON, OrgHunesionAppPlaybackSkeletonClass))
#define IS_org_hunesion_app_playback_SKELETON(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), TYPE_org_hunesion_app_playback_SKELETON))
#define IS_org_hunesion_app_playback_SKELETON_CLASS(k) (G_TYPE_CHECK_CLASS_TYPE ((k), TYPE_org_hunesion_app_playback_SKELETON))

typedef struct _OrgHunesionAppPlaybackSkeleton OrgHunesionAppPlaybackSkeleton;
typedef struct _OrgHunesionAppPlaybackSkeletonClass OrgHunesionAppPlaybackSkeletonClass;
typedef struct _OrgHunesionAppPlaybackSkeletonPrivate OrgHunesionAppPlaybackSkeletonPrivate;

struct _OrgHunesionAppPlaybackSkeleton
{
  /*< private >*/
  GDBusInterfaceSkeleton parent_instance;
  OrgHunesionAppPlaybackSkeletonPrivate *priv;
};

struct _OrgHunesionAppPlaybackSkeletonClass
{
  GDBusInterfaceSkeletonClass parent_class;
};

GType org_hunesion_app_playback_skeleton_get_type (void) G_GNUC_CONST;

#if GLIB_CHECK_VERSION(2, 44, 0)
G_DEFINE_AUTOPTR_CLEANUP_FUNC (OrgHunesionAppPlaybackSkeleton, g_object_unref)
#endif

OrgHunesionAppPlayback *org_hunesion_app_playback_skeleton_new (void);


G_END_DECLS

#endif /* __PLAYBACK_H__ */
